# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI-CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI Pipeline

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml


  deploy:
    name: CD Pipeline

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
        node-version: [ '12.x' ]
        appname: [ 'aws-codedeploy' ]
        deploy-group: [ 'staging' ]
        s3-bucket: [ 'aws-codedeploy-deployments-try' ]
        s3-filename: [ 'staging-aws-codedeploy-try-${{ github.sha }}' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run AWS CLI v1.19.59 commands
        uses: GuillaumeFalourd/aws-clis-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
        with:
          args: s3 ls

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
          --region us-east-2
          --application-name aws-codedeploy \
          --description "This is a revision for the aws-codedeploy-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://aws-codedeploy-deployments-try/staging-aws-codedeploy-dc1ad63e3952d6515378dedcc10a91f123544abd.zip \
          --source .

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name aws-codedeploy \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name tp-market-data-service \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=aws-codedeploy-deployments-try,key=staging-aws-codedeploy-dc1ad63e3952d6515378dedcc10a91f123544abd.zip,bundleType=zip \
